grade_1_question = [
    'I have a pet _____',
    'The _____ is shinning',
    'I _____ a book',
    'She is my _____',
    'We _____ to school',
    'She _____ to school every day.',
    'This is my friend. _____ name is John.',
    'It is a _____ day outside.',
    'The cat is _____ the table.',
    'What _____ John doing?',
    'What is the plural form of "child"?',
    'What is the past tense of "run"?',
    'What is the superlative form of "good"?',
    'Bill and I _____ here',
    'Mary’s _____ the garden',
    'Our house is _____ Washington Street',
    'James is talking to _____',
    'Sarah _____ cat',
    'Where _____ Mary standing?',
    'John, what _____ doing?'
]

grade_1_choice = [
    ['is', 'run', 'dog', 'and', 'dog'],
    ['run', 'sun', 'blue', 'and', 'sun'],
    ['reading', 'reads', 'read', 'readed', 'read'],
    ['and', 'run', 'blue', 'friend', 'friend'],
    ['go', 'goes', 'going', 'goed', 'go'],
    ['go', 'goes', 'going', 'goed', 'goes'],
    ['He', 'His', 'Him', 'It', 'His'],
    ['sunny', 'run', 'blue', 'and', 'sunny'],
    ['on', 'in', 'over', 'under', 'on'],
    ['are', 'do', 'does', 'is', 'is'],
    ['childs', 'childrens', 'childs', 'children', 'children'],
    ['runned', 'runned', 'ran', 'run', "ran"],
    ['gooder', 'goodest', 'more good', 'best', 'best'],
    ['we\'re', 'we', 'we are', 'are', 'are'],
    ['in', 'at', 'on', 'into', 'in'],
    ['in', 'from', 'at', 'on', 'from'],
    ['they', 'them', 'she', 'your', 'them'],
    ['haves a', 'haves some', 'has some', 'has a', 'has a'],
    ['do', 'does', 'is', 'are', 'is'],
    ['are you', 'is', 'your', 'he’s', 'are you']
]
